scraper:
  max_retries: 5
  timeout: 10
  delay_between_requests: 2

  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Language: en-US,en;q=0.9
    Accept-Encoding: gzip, deflate, br
    #Referer: https://google.com/
    Connection: keep-alive
    #Cache-Control: max-age=0
    #Upgrade-Insecure-Requests: 1
