[project]
name = "tradeitscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "asyncio>=4.0.0",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
]
